### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koipkoi** [poketony/pokeruby-kr#1]
## 레이아웃
- [x] 포켓몬 상태 화면
- [x] 파티 목록 화면
![pokeruby_01](https://github.com/poketony/pokeruby-kr/assets/39587773/d69bc205-52e9-4577-801f-dba9725822a6)

- [x] 타이틀 bg, sprite 오프셋
![pokeruby_01](https://github.com/poketony/pokeruby-kr/assets/39587773/9cb5aa86-2bdd-4284-8804-03d0550a6a4a)

- [x] 메인메뉴 (정보 오프셋, 단위 표시)
![pokeruby_03](https://github.com/poketony/pokeruby-kr/assets/39587773/d1ea892e-8ede-46d1-b659-c6caf9213a4b)

- [x] 가방 설명 오프셋
![pokeruby_04](https://github.com/poketony/pokeruby-kr/assets/39587773/10de8778-3e99-41f2-88a1-f9e1d3baaf4e)

## 시스템
- [x] 대화창
![pokeruby_02](https://github.com/poketony/pokeruby-kr/assets/39587773/2aab5352-de07-4286-970c-c15e03a02fe8)

- [x] 메뉴 (커서 스타일)
![pokeruby_03](https://github.com/poketony/pokeruby-kr/assets/39587773/4e3e432b-2353-42e8-8280-4413ec8b499a)

- [x] 설정화면 깨짐
![293691402-f3c51ded-2985-4a00-ad54-d4a9decc1058](https://github.com/poketony/pokeruby-kr/assets/39587773/411da80f-1d29-42be-97db-927b592fba00)

- [x] 포켓몬 이름 위치 조정, 비어있는 항목의 텍스트를 하이픈('-') 5자로 변경
![pokeruby_02](https://github.com/poketony/pokeruby-kr/assets/39587773/46608390-f3b8-43d8-8f80-63e0ab5b6340)

**Comment by koipkoi** [comment]
- [ ] 설정 화면 텍스트 위치 조정
![pokeruby_01](https://github.com/poketony/pokeruby-kr/assets/39587773/f3c51ded-2985-4a00-ad54-d4a9decc1058)

**Comment by koipkoi** [comment]
- [ ] 세이브 내용 변경
![pokesapphire_modern_02](https://github.com/poketony/pokeruby-kr/assets/39587773/284702ba-a807-4a81-b126-e286eebf0431)

- [ ] 전투 메시지 상자 gfx 변경
- [ ] 전투 HP, LV 폰트 변경
![pokesapphire_modern_01](https://github.com/poketony/pokeruby-kr/assets/39587773/5118d45e-1872-46cd-b0d7-4de04532b7cd)
